states = {
	'Alabama': 'AL',
	'Alaska': 'AK',
	'Arizona': 'AZ',
	'Arkansas': 'AR',
	'American Samoa': 'SA',
	'California': 'CA',
	'Colorado': 'CO',
	'Connecticut': 'CT',
	'Delaware': 'DE',
	'District of Colubmia': 'DC',
	'Florida': 'FL',
	'Georgia': 'GA',
	'Hawaii': 'HI',
	'Idaho': 'ID',
	'Illinois': 'IL',
	'Indiana': 'IN',
	'Iowa': 'IA',
	'Kansas': 'KS',
	'Kentucky': 'KY',
	'Louisiana': 'LA',
	'Maine': 'ME',
	'Maryland': 'MD',
	'Massachusetts': 'MA',
	'Michigan': 'MI',
	'Minnesota': 'MN',
	'Mississippi': 'MS',
	'Missouri': 'MO',
	'Montana': 'MT',
	'Nebraska': 'NE',
	'Nevada': 'NV',
	'New Hampshire': 'NH',
	'New Jersey': 'NJ',
	'New Mexico': 'NM',
	'New York': 'NY',
	'North Carolina': 'NC',
	'North Dakota': 'ND',
	'Ohio': 'OH',
	'Oklahoma': 'OK',
	'Oregon': 'OR',
	'Pennsylvania': 'PA',
	'Rhode Island': 'RI',
	'South Carolina': 'SC',
	'South Dakota': 'SD',
	'Tennessee': 'TN',
	'Texas': 'TX',
	'Utah': 'UT',
	'Vermont': 'VT',
	'Virginia': 'VA',
	'Virgin Islands': 'VI',
	'Washington': 'WA',
	'West Virginia': 'WV',
	'Wisconsin': 'WI',
	'Wyoming': 'WY'

}

cities = {
	'AL': ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa', 'Hoover'],
	'AK': ['Anchorage'],
	'AZ': ['Pheonix', 'Tucson', 'Mesa', 'Chandler', 'Glendale', 'Scottsdale', 'Gilbert', 'Tempe', 'Peoria', 'Surprise', 'Yuma', 'Avondale'],
	'AR': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro'],
	'CA': ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Chula Vista', 'Fremont', 'Irvine', 'San Bernardino', 'Modesto', 'Oxnard', 'Fontana', 'Moreno Valley', 'Glendale', 'Huntington Beach', 'Santa Clarita', 'Garden Grove', 'Santa Rosa', 'Oceanside', 'Rancho Cucamonga', 'Ontario', 'Lancaster', 'Elk Grove', 'Palmdale', 'Corona', 'Salinas', 'Pomona', 'Torrance', 'Hayward', 'Escondido', 'Sunnvale', 'Pasadena', 'Orange', 'Fullerton', 'Thousand Oaks', 'Visalia', 'Simi Valley', 'Concord', 'Roseville', 'Santa Clara', 'Vallejo', 'Victorville', 'El Monte', 'Berkeley', 'Downey', 'Costa Mesa', 'Inglewood', 'Ventura', 'West Covina', 'Norwalk', 'Carlsbad', 'Fairfield', 'Richmond', 'Murrieta', 'Burbank', 'Antioch', 'Daly City', 'Temecula', 'Santa Maria', 'El Cajon', 'Rialto', 'San Mateo', 'Compton', 'Clovis', 'South Gate', 'Vista', 'Mission Viejo', 'Vacaville', 'Carson', 'Hesperia', 'Redding', 'Santa Monica', 'Westminster', 'Santa Barbara', 'Chico', 'Whittier', 'Newport Beach', 'San Leandro', 'Hawthorne', 'San Marcos', 'Citrus Heights', 'Alhambra', 'Tracy', 'Livermore', 'Buena Park', 'Lakewood', 'Merced', 'Hemet', 'Chino', 'Menifee', 'Lake Forest', 'Napa', 'Redwood City', 'Bellflower', 'Indio', 'Tustin', 'Baldwin Park', 'Chino Hills', 'Mountain View', 'Alameda', 'Upland', 'Folsom', 'San Ramon', 'Pleasanton', 'Lynwood', 'Union City', 'Apple Valley', 'Redlands', 'Turlock', 'Perris', 'Manteca', 'Milpitas', 'Redondo Beach'],
	'CO': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Pueblo', 'Arvada', 'Westminster', 'Centennial', 'Boulder', 'Greeley', 'Longmont', 'Loveland'],
	'CT': ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury', 'Norwalk', 'Danbury', 'New Britain'],
	'DE': ['Wilmington'],
	'DC': ['Washington'],
	'FL': ['Jacksonville', 'Miami', 'Tampa', 'St. Petersburg', 'Orlando', 'Hialeah', 'Tallahassee', 'Ft. Lauderdale', 'Port St. Lucie', 'Pembroke Pines', 'Cape Coral', 'Hollywood', 'Gainesville', 'Miramar', 'Coral Springs', 'Clearwater', 'Miami Gardens', 'Palm Bay', 'West Palm Beach', 'Pompano Beach', 'Lakeland', 'Davie', 'Miami Beach', 'Deltona', 'Plantation', 'Sunrise', 'Boca Raton', 'Largo', 'Melbourne', 'Palm Coast', 'Deerfield', 'Boynton Beach', 'Lauderhill'],
	'GA': ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Athens', 'Sandy Springs', 'Macon', 'Roswell', 'Albany', 'Johns Creek', 'Warner Robins'],
	'HI': ['Honolulu'],
	'ID': ['Boise City', 'Nampa', 'Meridian'],
	'IL': ['Chicago', 'Aurora', 'Rockford', 'Joilet', 'Naperville', 'Springfield', 'Peoria', 'Elgin', 'Waukegan', 'Cicero', 'Champaign', 'Bloomington', 'Decatur', 'Arlington Heights', 'Evanston', 'Schaumburg', 'Bolingbrook', 'Palatine'],
	'IN': ['Indianapolis', 'Ft. Wayne', 'Evansville', 'South Bend', 'Hammond', 'Bloomington', 'Gary', 'Carmel', 'Fishers', 'Muncie', 'Lafayette'],
	'KS': ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe', 'Lawrence'],
	'KY': ['Louisville', 'Lexington'],
	'LA': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles', 'Kenner'],
	'ME': ['Portland'],
	'MA': ['Boston', 'Worchester', 'Springfield', 'Lowell', 'Cambridge', 'New Bedford', 'Brockton', 'Quincy', 'Lynn', 'Fall River', 'Newton', 'Lawrence', 'Somerville'],
	'MI': ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Lansing', 'Ann Arbor', 'Flint', 'Dearborn', 'Livonia', 'Westland', 'Troy', 'Farmington Hills', 'Kalamazoo', 'Wyoming', 'Southfield', 'Rochester Hills'],
	'MN': ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park', 'Plymouth'],
	'MS': ['Jackson', 'Gulfport'],
	'MO': ['Kansas City', 'St. Louis', 'Springfield', 'Independence', 'Columbia', "Lee's Summit", "O'Fallen", 'St. Joseph'],
	'MN': ['Billings', 'Missoula'],
	'NE': ['Omaha', 'Lincoln'],
	'NV': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'],
	'NH': ['Manchester', 'Nashua'],
	'NJ': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton', 'Clifton', 'Camden', 'Passaic', 'Union City'],
	'NM': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Sante Fe'],
	'NY': ['New York', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady'],
	'NC': ['Charlotte', 'Raleigh', 'Greensboro', 'Winston-Salem', 'Durham', 'Fayetteville', 'Cary', 'Wilmington', 'High Point', 'Greenville', 'Asheville', 'Concord', 'Gastonia', 'Jacksonville'],

}

input_ = "> "

state__ = input(input_)

print(f"{states[state__]}")


